// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package messageServ

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	OpenMessageChannel(ctx context.Context, opts ...grpc.CallOption) (MessageService_OpenMessageChannelClient, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) OpenMessageChannel(ctx context.Context, opts ...grpc.CallOption) (MessageService_OpenMessageChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[0], "/messageServ.MessageService/OpenMessageChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceOpenMessageChannelClient{stream}
	return x, nil
}

type MessageService_OpenMessageChannelClient interface {
	Send(*MessageRequest) error
	Recv() (*MessageResponse, error)
	grpc.ClientStream
}

type messageServiceOpenMessageChannelClient struct {
	grpc.ClientStream
}

func (x *messageServiceOpenMessageChannelClient) Send(m *MessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageServiceOpenMessageChannelClient) Recv() (*MessageResponse, error) {
	m := new(MessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	OpenMessageChannel(MessageService_OpenMessageChannelServer) error
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) OpenMessageChannel(MessageService_OpenMessageChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenMessageChannel not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_OpenMessageChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServiceServer).OpenMessageChannel(&messageServiceOpenMessageChannelServer{stream})
}

type MessageService_OpenMessageChannelServer interface {
	Send(*MessageResponse) error
	Recv() (*MessageRequest, error)
	grpc.ServerStream
}

type messageServiceOpenMessageChannelServer struct {
	grpc.ServerStream
}

func (x *messageServiceOpenMessageChannelServer) Send(m *MessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageServiceOpenMessageChannelServer) Recv() (*MessageRequest, error) {
	m := new(MessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messageServ.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenMessageChannel",
			Handler:       _MessageService_OpenMessageChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "messageServ/msg.proto",
}
